Error: do not call reason `ooni_error`
Okay, currently we have the reason which is equal to `ooni_error` but
that would not necessarily be the case in future.

So, leave `as_ooni_error()` as the preferred way to know the OONI error
string and use `reason` (more neutral) for the attribute.